<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
		<Description>授权中心核心库</Description>
		<Version>2026.1.127</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Quick.Shell" Version="1.0.4" />
  </ItemGroup>

</Project>
