<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UseAppHost>false</UseAppHost>
		<RollForward>Major</RollForward>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="YiQiDong.Core" Version="2026.14.320" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\KeyCenter.Core\KeyCenter.Core.csproj" />
	</ItemGroup>

</Project>
